### ISSUE TITLE
Readme improvements.

### ISSUE THREAD

**Issue by macdja38** [aliasfalse/warframe-worldstate-parser#29]
Change getAlertsAsString to getAlertsString in the readme, or vice versa in the files. And make a not in the readme that it's not done yet and currenttly commented out. Also do this to a ton of other things.

and a simple example of how to import this project and include it might be nice.

Also the installation instruction should include the npm command to install from the github if that is the recomended version to use as expressed in the Readme.

**Comment by aliasfalse** [comment]
Npm command: it is in the npm badge at the top of the readme  and at the bottom.. I'm looking over the rest.
Please don't use wording like "and a ton of other things" if you want it to be used.

**Comment by aliasfalse** [comment]
#30 that work for you?

**Comment by macdja38** [comment]
Yup, that seems to fix most of the issues. I mean it would be nice to have the npm command that installs this from the github rather than the npm repo included in the installation section, based on what is listed in the note.

**Comment by aliasfalse** [comment]
I have a change I'm making that will make it easier to maintain upstream, where we're breaking the actual data files into their own module and this will be dependent on the latest version of the data module.

**Comment by aliasfalse** [comment]
Basically, I'm adding it now because i'd be removing it with the next release anyway.
