### ISSUE TITLE
Error whilst running Usage code provided by README

### ISSUE THREAD

**Issue by Cp-022** [aliasfalse/warframe-worldstate-parser#34]
Tried to test how it works (since there isn't much to read about) by running the code provided by the README
```
var WorldState = require('warframe-worldstate-parser');
var worldStates = {
  PC : new Worldstate('PC'),
  PS4 : new Worldstate('PS4'),
  X1 : new Worldstate('X1'),
}
var primeAccess = null;
worldStates[PC].getPrimeAccessString(function(err, primeAccessObject) {
  if (err) {
    return console.err(err);
  }
  primeAccess = primeAccessObject;
});
```
Sadly after running it I got the following error
```
ReferenceError: Worldstate is not defined
    at Object.<anonymous> (removedForObviousReasons\test.js:3:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

I'm sorry if I misunderstood something of the code that is provided.

EDIT: Grammar and markup fix

**Comment by aliasfalse** [comment]
It's definitely a typo in the test code. From the JSON and attempt to call:
```diff
- Worldstate
```

From the require:
```diff
+ WorldState
```

**Comment by aliasfalse** [comment]
Capitalization win.

**Comment by aliasfalse** [comment]
Feel free to contact me on Discord if you'd like, and you use the application.
My id is `Tobiah#8452`

**Comment by Cp-022** [comment]
I ran the preview code agan, following the steps you said it still gave me the same error, so I tried the following:
```
var Worldstate = require('warframe-worldstate-parser');
var worldStates = {
  PC : new WorldState('PC'),
  PS4 : new WorldState('PS4'),
  X1 : new WorldState('X1'),
}
var primeAccess = null;
worldStates[PC].getPrimeAccessString(function(err, primeAccessObject) {
  if (err) {
    return console.err(err);
  }
  primeAccess = primeAccessObject;
});
```
This resulted in the following error:
```
hidden for obvious reasons\node_modules\warframe-worldstate-parser\src\modules\news.js:14
  for (var index = 0; index < data.length; index++){
                                  ^

TypeError: Cannot read property 'length' of undefined
    at new News (hidden for obvious reasons\node_modules\warframe-worldstate-parser\src\modules\news.js:14:35)
    at new WorldState (hidden for obvious reasons\node_modules\warframe-worldstate-parser\src\worldstate.js:23:15)
    at Object.<anonymous> (hidden for obvious reasons\try.js:3:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```
Hope this helps

**Comment by aliasfalse** [comment]
doesn't particularly help at  all. which branch did you install when you ran `npm install`?

**Comment by aliasfalse** [comment]
Are you allowing node access to the internet?

**Comment by Cp-022** [comment]
Node has internet access, I tried both the github master branch and the npm version
Both seem to give the exact same error

**Comment by aliasfalse** [comment]
on the data module, you have to install it separately if you're going to use it in that manner because parser pulls it in on its own. 
In addition, it doesn't look like you're setting the result of the require to anything, which is why you can't access any of it's properties.

where you do
`primeAccess = primeAccessObject;`

change it to

`console.log(primeAccessObject);`
just to see what you get if the code ever reaches there.

**Comment by aliasfalse** [comment]
RunKit probably doesn't pull in the transitive dependencies correctly, would be my guess.

**Comment by Cp-022** [comment]
Your suggestion still gave me the same error regarding news.js,
So I tried to comment every inclusion of news.js and ran it but this time it gave me an error of sorties.js.
Both news.js  and worldstate.js run perfectly fine alone, but if I try to call them  via the readme example 
it just gives the usual error of undefined .length

**Comment by aliasfalse** [comment]
Sorry I haven't helped you in so long. Have you been able to figure anything out?

**Comment by Cp-022** [comment]
Havn't been able to figure anything new out. 
Only thing to note is that when I comment out sortie.js it then continous to give me an error of the next require which in this case is globalModifiers.js. The error usually contains an undefined length of the data array.
I will try to uninstall and reinstall the package to see if the problem reoccurs.

**Comment by aliasfalse** [comment]
Just so you know, I haven't forgotten, I'm looking into it still and working on  reproducing your error.

**Comment by aliasfalse** [comment]
@Cp-022 I got it figured out. I'm updating the sample doc, because this was totally a flub on my part.

**Comment by Cp-022** [comment]
Got it working, thanks for the patience!

**Comment by aliasfalse** [comment]
No problem, I'm sorry it took me so long to find that.
